# Compiler
CXX = g++

# Compiler Flags
CXXFLAGS = -Wall -std=c++11

# Source Files
SOURCES = graphicsworld.cpp point.cpp shape.cpp square.cpp rectangle.cpp exeBmain.cpp circle.cpp

# Output File
OUTPUT = myprogram

all:
	$(CXX) $(CXXFLAGS) $(SOURCES) -o $(OUTPUT)

clean:
	rm -f $(OUTPUT)
